FROM dragoncube/google-domains-ddns
LABEL maintainer="gagandaroach@gmail.com"
COPY ./google-domains-ddns.conf /config
# ARG name=UID
# ARG name=GUID
# USER ${UID:-1000}:${GUID:-1000}
#docker run --name=googleDNS -d -v /etc/localtime:/etc/localtime -v googleDNS:/config --net daroachnet -e PGID=1000 -e PUID=1000 dragoncube/google-domains-ddns 
