# daroach.net
# Docker containers running on my homelab.
#
# portainer.daroach.net | admin for docker containers
# Author: Gagan Daroach gagandaroach@gmail.com
version: "3"

networks:
  daroachnetwork:
    external: true

services:
  portainer:
    restart: ${RESTART}
    image: portainer/portainer-ce
    ports:
      - "20000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_MOUNT_POINT}:/data
    environment:
      - VIRTUAL_HOST=portainer.daroach.net
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    command: -H unix:///var/run/docker.sock
    networks:
      - daroachnetwork
