version: '2'

networks:
  daroachnetwork:
    external: true
  chat_net:

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://salmon.daroach.net
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
      - VIRTUAL_HOST=salmon.daroach.net
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=salmon.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    networks:
      - daroachnetwork
      - chat_net
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    networks:
      - chat_net
    # ports:
    #   - 27017:27017

  # mongo-init-replica:
  #   image: mongo:4.0
  #   command: >
  #     bash -c
  #       "for i in `seq 1 30`; do
  #         mongo mongo/rocketchat --eval \"
  #           rs.initiate({
  #             _id: 'rs0',
  #             members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
  #         s=$$? && break || s=$$?;
  #         echo \"Tried $$i times. Waiting 5 secs...\";
  #         sleep 5;
  #       done; (exit $$s)"
  #   networks:
  #     - chat_net
  #   depends_on:
  #     - mongo

