# daroach.net
#
# VueJS Nuxt Web Server
#
# Author: Gagan Daroach gagandaroach@gmail.com
version: "3"

networks:
  default:
    external: true
    name: daroachnetwork

services:
  webserver:
    build: ./nuxt_webserver
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=www.daroach.net
      - LETSENCRYPT_HOST=www.daroach.net
      - VIRTUAL_PORT=3000
    command: "npm run start"
    # ports:
      # - 80:3000
      # - 3000:3000

  redirect:
    image: morbz/docker-web-redirect
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=daroach.net
      - REDIRECT_TARGET=www.daroach.net
      - LETSENCRYPT_HOST=www.daroach.net
      - VIRTUAL_PORT=80
