version: "3"

networks:
  default:
    external: false

services:
  # daroach.net
  ddns-daroachnet:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CONF_FILE: daroach.net.conf
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime

  # medschooldreams.com
  ddns-medschooldreamscom:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CONF_FILE: medschooldreams.com.conf
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime

  # hsulympics.com
  ddns-hsulympicscom:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CONF_FILE: hsulympics.com.conf
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
